# This pipeline builds all the C# projects found in the project
name: 1.0.$(Date:Mdd)$(rev:r) # This is the build number

trigger:
- adina-main

pr:
 branches:
    include:
    - adina*

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build C# project'
  inputs:
    command: 'build'
    projects: '**/*.csproj' # Builds all the csproj found in the project

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj' # Runs all the tests found in the project
